name: Health Check

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: From Scratch Test
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dynamic dependencies
      run: |
        wget https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz -O /tmp/zeromq.tar.gz
        tar -xzvf /tmp/zeromq.tar.gz -C /tmp && cd /tmp/zeromq-* && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_CURVE=ON .. && make && sudo make install

    - name: Install static dependencies (unit)
      run: |
        cd services/ledger-unit
        GO111MODULE=on go mod verify
        GO111MODULE=on go mod tidy
        GO111MODULE=on go mod vendor

    - name: Install static dependencies (rest)
      run: |
        cd services/ledger-rest
        GO111MODULE=on go mod verify
        GO111MODULE=on go mod tidy
        GO111MODULE=on go mod vendor

    - name: Unit Test (unit)
      run:  |
        cd services/ledger-unit
        go test -v ./... -timeout=10s

    - name: Unit Test (rest)
      run:  |
        cd services/ledger-rest
        go test -v ./... -timeout=10s
